### ISSUE TITLE
add separator to context menu

### ISSUE THREAD

**Issue by raingart** [w3lifer/crx-context-menu-search#1]
etc extension: https://chrome.google.com/webstore/detail/context-menu-search/lhneenlgkagogapgbkjbjdfelpghbnak

there is an interesting, feature implemented - "separator" 
if you look into background.js:38

```
if (links[id].name[0] == "-") {
        chrome.contextMenus.create({
                            type: "separator",
                            contexts: ['selection'],
                            parentId: parentMenuItem
                        });
                    }                
```

I would like you to add it. Thanks!

**Comment by w3lifer** [comment]
Due to the complexity of implementation and lack of time,.. use hyphens (`---------`).

**Comment by raingart** [comment]
> Due to the complexity of implementation and lack of time,.. use hyphens (`---------`).

seriously? Just replase the
`chrome.contextMenus.create({
        id: index,
        title: fieldsets[index].name,
        contexts: ['selection']
      });`
in js/common.js:42

on this:
```
var a = {
        id: index,
        title: fieldsets[index].name,
        contexts: ['selection']
      };
if ( fieldsets[index].name.startsWith('--') ) a.type = "separator";

 chrome.contextMenus.create(a);
```

**Comment by raingart** [comment]
@w3lifer уже год прошел, думаю можно и добавить гребанный разделитель в расширение.Я даже код прикрепил что нужно добавить. Так что не думаю что могут быть хоть какие то проблемы в реализации.

Да и еще. Зачем в manifest.json нужны права "permissions": [ "downloads"] а?

**Comment by w3lifer** [comment]
@raingart, добавлю: я загулял пока. `"permissions": [ "downloads"]` нужен, что импортировать экспортированные поиски.

**Comment by w3lifer** [comment]
@raingart, добавил, сейчас залью в стор. Главное, чтобы ничего не поломалось)

**Comment by raingart** [comment]
@w3lifer сломалось. Точнее не заработало.
забыли добавить - type: "separator"
https://github.com/w3lifer/crx-context-menu-search/commit/641cc0175ebb2017c87467ab6e4a8b1a37f22098#r49708344

**Comment by w3lifer** [comment]
Done.
