### ISSUE TITLE
Escaping Special Characters "&"

### ISSUE THREAD

**Issue by raingart** [w3lifer/crx-context-menu-search#2]
incorrectly accept argument convert to type GET

example if search:
"bla1 & bla2" => test.com/results?search_query=bla1%20&%20bla2

expected behavior:
"bla1 & bla2" => test.com/results?search_query=bla1%20%26%20bla2

encodeURI('&') => "&"
escape('&') => "%26"

**Comment by w3lifer** [comment]
@raingart, note, that some sites/services still replace "%26" to "&". For examle, Google, YouTube, Facebook, Yandex Maps, etc.

GitHub, for example, does not replace it: https://github.com/search?q=bla1%20%26%20bla2.

**Comment by w3lifer** [comment]
Done!
